### ISSUE TITLE
namespace dereferencable https://w3id.org/pmd/tto 

### ISSUE THREAD

**Issue by joergwa** [materialdigital/application-ontologies#20]
Make namespace dereferencable for https://w3id.org/pmd/tto 

You might use the publication workflow from pmdco to publish a documentation in the github pages of your repo.

Register the namespace with w3id, in the same way like pmd/co
https://github.com/perma-id/w3id.org/tree/master/pmd

Here you have to adapt the .htaccess file to fit your redirect location. 
(see pmd/glass-ontology for example)

**Comment by MattTJung** [comment]
Hi,

it would be great if you already keep in mind, that there are more namespaces to come, like hto, hmo, ...
For each one of those the namespace should be registered and a doc should be generated.

See you

**Comment by MattTJung** [comment]
@joergwa about the docs: Could you have a look at https://github.com/MattTJung/application-ontologies/tree/hmo_documentation? I added an action to publish docs for hmo and tto to https://matttjung.github.io/application-ontologies/hmo/ and https://matttjung.github.io/application-ontologies/tto/, respectively. Do you think that's a valid way to go? I think the https://github.com/MattTJung/application-ontologies/blob/hmo_documentation/.github/workflows/deploy.yaml could be more clean, but for now it mostly seems to work.

**Comment by MarkusSchilling** [comment]
The namespace [https://w3id.org/pmd/tto](https://w3id.org/pmd/tto) is now dereferencable which was realized in the way proposed here. Furthermore, the documentation page (using gh-pages: [tto](https://materialdigital.github.io/application-ontologies/tto/index-en.html#) is automatically updated by GitHub actions when changes are pushed.
