### ISSUE TITLE
Missing concepts for cross-sectional area

### ISSUE THREAD

**Issue by MattTJung** [materialdigital/application-ontologies#38]
Hi,

the current definition of https://w3id.org/pmd/tto/PercentageReductionOfArea says, that it is related to some Thickness+Width or some Diameter. The cited definition from the standard DIN EN ISO 6892-1 uses the symbols S_o and S_u (original cross-sectional area and cross-sectional area after fracture). I think it would be beneficial to define the concepts of S_o and S_u. The relation to Thickness+Width/Diameter implies, that the cross-section is either rectangular or circular. But, the standard allows for an arbitrary cross-sectional shape as long as it's uniform along the parallel length. Also, circular cross-sections are usually interpreted as ellipses when measuring (see ASTM E8/E8M [^1]).

BR
Matthias

[^1]: ASTM E8/E8M - 21: NOTE 46—Because of anisotropy, circular cross-sections often do not remain circular during straining in tension. The shape is usually elliptical, thus, the area may be calculated by π · d1·d2/4, where d1 and d2 are the major and minor diameters, respectively.

**Comment by MarkusSchilling** [comment]
That is a very good idea. Thank you for the contribution. The concepts of "Original cross-sectional area of the parallel length" and "Minimum cross-sectional area after fracture" were added to pmd_tto.ttl. The definition of [https://w3id.org/pmd/tto/PercentageReductionOfArea](https://w3id.org/pmd/tto/PercentageReductionOfArea) was adjusted, accordingly.

This was part of [PR #41](https://github.com/materialdigital/application-ontologies/pull/41) and the respective [commit](https://github.com/materialdigital/application-ontologies/commit/b559db62a3569b3cd7caf31dbb76625153a4c0e3).
